esphome:
  name: quietcool-attic-fan
  friendly_name: "Attic Fan"
  on_boot:
    priority: 800  # Run after full boot
    then:
      # Boot animation - cascade LEDs to show successful startup
      - delay: 1s
      - light.turn_on: left_led
      - light.turn_on: middle_led
      - light.turn_on: right_led
      - delay: 1s
      - light.turn_off: right_led
      - delay: 0.5s
      - light.turn_off: middle_led
      - delay: 0.5s
      - light.turn_off: left_led

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot in case WiFi connection fails
  ap:
    ssid: "Attic-Fan Fallback"
    password: !secret ap_password

# Enable web server for direct access
web_server:
  port: 80

# Enable captive portal for WiFi setup
captive_portal:

# Front panel buttons (optional - you can remove this section if not using buttons)
binary_sensor:
  - platform: gpio
    name: "High Speed Button"
    pin:
      number: GPIO26
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      - switch.turn_on: high_speed
      
  - platform: gpio
    name: "Low Speed Button"
    pin:
      number: GPIO27
      inverted: true
      mode:
        input: true
        pullup: true
    on_press:
      - switch.turn_on: low_speed

# LED indicators
light:
  # Right LED - originally for Bluetooth status
  - platform: binary
    name: "Bluetooth LED"
    output: right_led_output
    id: right_led
    restore_mode: ALWAYS_OFF
    
  # Middle LED - shows fan speed with blinking pattern
  - platform: binary
    name: "Speed LED"
    output: middle_led_output
    id: middle_led
    restore_mode: ALWAYS_OFF
    effects:
      - strobe:
          name: Low Speed
          colors:
            - state: true
              brightness: 100%
              duration: 150ms
            - state: false
              duration: 1000ms
      - strobe:
          name: High Speed
          colors:
            - state: true
              brightness: 100%
              duration: 150ms
            - state: false
              duration: 150ms
            - state: true
              brightness: 100%
              duration: 150ms
            - state: false
              duration: 1000ms
              
  # Left LED - general status indicator
  - platform: binary
    name: "Status LED"
    output: left_led_output
    id: left_led
    restore_mode: ALWAYS_OFF

# LED output definitions
output:
  - id: right_led_output
    platform: gpio
    pin: 
      number: GPIO32
      inverted: true
      
  - id: middle_led_output
    platform: gpio
    pin:
      number: GPIO33
      inverted: true
      
  - id: left_led_output
    platform: gpio
    pin:
      number: GPIO25
      inverted: true
  
  # Template output for fan entity (used if fan section below is uncommented)
  - platform: template
    id: fan_output
    type: float
    write_action:
      - if:
          condition:
            lambda: 'return state == 0;'
          then:
            - switch.turn_off: low_speed
            - switch.turn_off: high_speed
      - if:
          condition:
            lambda: 'return state > 0 && state <= 0.5;'
          then:
            - switch.turn_on: low_speed
      - if:
          condition:
            lambda: 'return state > 0.5;'
          then:
            - switch.turn_on: high_speed

# Fan speed control relays with interlock
# Interlock ensures only one speed can be active at a time
switch:
  - platform: gpio
    pin: GPIO5
    name: "Low Speed"
    id: low_speed
    restore_mode: ALWAYS_OFF
    interlock: &interlock_group [low_speed, high_speed]
    interlock_wait_time: 2s
    on_turn_on:
      - light.turn_on:
          id: middle_led
          effect: "Low Speed"
    on_turn_off:
      - light.turn_off: middle_led
      
  - platform: gpio
    pin: GPIO23
    name: "High Speed"
    id: high_speed
    restore_mode: ALWAYS_OFF
    interlock: *interlock_group
    interlock_wait_time: 2s
    on_turn_on:
      - light.turn_on:
          id: middle_led
          effect: "High Speed"
    on_turn_off:
      - light.turn_off: middle_led

# I2C bus for temperature/humidity sensor
i2c:
  sda: GPIO18
  scl: GPIO19
  scan: true
  id: bus_a

# Temperature and humidity sensor (SHT3X)
sensor:
  - platform: sht3xd
    temperature:
      name: "Attic Temperature"
      id: attic_temp
      filters:
        # Convert from Celsius to Fahrenheit
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      # Fire safety shutoff at 182°F (matches stock firmware)
      on_value_range:
        above: 182
        then:
          - switch.turn_off: low_speed
          - switch.turn_off: high_speed
          - logger.log: "Emergency shutdown - temperature above 182°F"
    humidity:
      name: "Attic Humidity"
      id: attic_humidity
      accuracy_decimals: 1
    address: 0x44  # If sensor not found, try 0x45
    update_interval: 30s

  # WiFi signal strength monitoring
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Uptime sensor
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

# Create a proper fan entity in Home Assistant
fan:
  - platform: speed
    output: fan_output
    name: "Attic Fan"
    speed_count: 2
